tool.uv.package = true

[project]
name = "resonator"
version = "0.1.0"
description = "A distributed calculator built with Resonate."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "resonate-sdk>=0.4.8",
]

[project.scripts]
resonator = "resonator.resonator:run"
